# Generated by Django 5.1.5 on 2025-05-01 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('full_marks', models.IntegerField(default=100)),
                ('pass_marks', models.IntegerField(default=40)),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='classes.schoolclass')),
                ('subject_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee')),
            ],
            options={
                'unique_together': {('school_class', 'name')},
            },
        ),
    ]
