# Generated by Django 5.1.5 on 2025-02-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schooldata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('enroll_class', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('blood_group', models.CharField(blank=True, max_length=3, null=True)),
                ('religion', models.CharField(blank=True, max_length=50, null=True)),
                ('document1', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document2', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('document3', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('date_of_birth', models.DateField()),
                ('date_of_enrollment', models.DateTimeField(auto_now_add=True)),
                ('seq_no', models.PositiveIntegerField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schooldata.school')),
            ],
        ),
    ]
