# Generated by Django 5.1.5 on 2025-02-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_student_id_studentidcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_enrollment',
            field=models.DateTimeField(),
        ),
    ]
