# Generated by Django 5.1.5 on 2025-02-16 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_enrollment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
