# Generated by Django 5.1.5 on 2025-02-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_student_seq_no_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default=33, max_length=5),
            preserve_default=False,
        ),
    ]
