# Generated by Django 5.1.5 on 2025-02-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tuition_fee', models.FloatField()),
                ('class_teacher', models.CharField(max_length=100)),
            ],
        ),
    ]
