# Generated by Django 5.1.5 on 2025-02-17 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='principal_name',
            new_name='target_line',
        ),
    ]
