# Generated by Django 5.1.5 on 2025-02-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schooldata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='registration_code',
        ),
    ]
